import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { resolvePartyType } from "../app/domain.ts";

test("legacy party roles resolve centrally without changing valid roles",()=>{const parties=[{id:"a"},{id:"b",partyType:"supplier"},{id:"c",partyType:"customer"}];assert.deepEqual(parties.map(resolvePartyType),["supplier","supplier","customer"]);assert.deepEqual(parties.filter(p=>resolvePartyType(p)==="customer").map(p=>p.id),["c"]);assert.deepEqual(parties.filter(p=>resolvePartyType(p)==="supplier").map(p=>p.id),["a","b"]);});

test("POS and party workspaces retain compact role-safe structure and empty rows",async()=>{const source=await readFile(new URL("../app/conta-app.tsx",import.meta.url),"utf8"),css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(source,/className="pos-payment-row"/);assert.match(source,/resolvePartyType\(p\) === "customer"/);assert.match(source,/variant="pos-native" ariaLabel="العميل"/);assert.match(source,/searchable=\{false\} floating variant="pos-native" ariaLabel="الحساب البنكي"/);assert.match(source,/<bdi dir="ltr">\{party\.phone\|\|"—"\}<\/bdi>/);assert.match(source,/لا يوجد عملاء حتى الآن/);assert.match(source,/لا يوجد موردون/);assert.match(css,/\.pos-payment-row \{[^}]*display: flex[^}]*min-width: 0/s);assert.match(css,/\.compact-payment > button \{ flex: 0 0 50px/);assert.match(css,/\.bank-option \{ flex: 0 0 72px/);assert.match(css,/\.pos-customer-compact \{ flex: 1 1 auto/);assert.match(css,/\.pos-workspace \{ grid-template-columns: minmax\(0, 23fr\) minmax\(0, 42fr\) minmax\(0, 35fr\)/);assert.match(css,/\.section-parties, \.section-customers, \.section-suppliers/);});

test("comprehensive screen and print omit cash metrics and include bank detail",async()=>{const source=await readFile(new URL("../app/conta-app.tsx",import.meta.url),"utf8");assert.doesNotMatch(source,/إجمالي الداخل إلى الخزنة|إجمالي الخارج من الخزنة|رصيد الخزنة/);assert.match(source,/aria-expanded=\{bankOpen\}/);assert.match(source,/className="bank-detail print-only"/);assert.match(source,/فواتير البيع/);assert.doesNotMatch(source,/قيمة الفاتورة \(MRU\)|التكلفة \(MRU\)|الربح \(MRU\)/);assert.match(source,/<th>رقم<\/th><th>نوع الفاتورة<\/th><th>رقم الفاتورة/);});
