import type { Customer, MovementRecord, Product, SaleRecord } from "./domain";

export const demoProducts: Product[] = [
  {
    id: "p-sugar",
    name: "سكر ناعم 1 كغ",
    category: "مواد غذائية",
    sku: "SUG-001",
    barcode: "1001001001",
    piecesPerCarton: 20,
    pieceCost: 280,
    piecePrice: 350,
    cartonPrice: 6600,
    stock: { warehouse: 184, boutique: 57 },
    accent: "#d97706",
  },
  {
    id: "p-oil",
    name: "زيت نباتي 1 لتر",
    category: "مواد غذائية",
    sku: "OIL-014",
    barcode: "1001001002",
    piecesPerCarton: 12,
    pieceCost: 690,
    piecePrice: 800,
    cartonPrice: 9000,
    stock: { warehouse: 96, boutique: 31 },
    accent: "#eab308",
  },
  {
    id: "p-milk",
    name: "حليب طويل الأجل",
    category: "مشروبات",
    sku: "MLK-110",
    barcode: "1001001003",
    piecesPerCarton: 24,
    pieceCost: 250,
    piecePrice: 320,
    cartonPrice: 7200,
    stock: { warehouse: 240, boutique: 68 },
    accent: "#0ea5e9",
  },
  {
    id: "p-rice",
    name: "أرز بسمتي 5 كغ",
    category: "مواد غذائية",
    sku: "RIC-500",
    barcode: "1001001004",
    piecesPerCarton: 4,
    pieceCost: 1580,
    piecePrice: 1850,
    cartonPrice: 7000,
    stock: { warehouse: 52, boutique: 17 },
    accent: "#22c55e",
  },
  {
    id: "p-pasta",
    name: "معكرونة 500 غ",
    category: "مواد غذائية",
    sku: "PST-050",
    barcode: "1001001005",
    piecesPerCarton: 20,
    pieceCost: 130,
    piecePrice: 180,
    cartonPrice: 3300,
    stock: { warehouse: 160, boutique: 45 },
    accent: "#f97316",
  },
  {
    id: "p-cleaner",
    name: "مسحوق تنظيف 2 كغ",
    category: "مواد تنظيف",
    sku: "CLN-200",
    barcode: "1001001006",
    piecesPerCarton: 8,
    pieceCost: 540,
    piecePrice: 680,
    cartonPrice: 5100,
    stock: { warehouse: 40, boutique: 14 },
    accent: "#8b5cf6",
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "c-001",
    name: "محمد ولد أحمد",
    phone: "22 33 44 55",
    balance: 18400,
    creditLimit: null,
    lastActivity: "اليوم",
  },
  {
    id: "c-002",
    name: "مريم بنت سالم",
    phone: "36 11 09 40",
    balance: 7200,
    creditLimit: null,
    lastActivity: "أمس",
  },
  {
    id: "c-003",
    name: "متجر الأمانة",
    phone: "48 02 54 50",
    balance: 0,
    creditLimit: null,
    lastActivity: "منذ 3 أيام",
  },
];

export const demoSales: SaleRecord[] = [
  {
    id: "V-1048",
    createdAt: "11:42",
    total: 9850,
    paymentMethod: "cash",
    customerName: "زبون نقدي",
    itemCount: 4,
  },
  {
    id: "V-1047",
    createdAt: "11:18",
    total: 7200,
    paymentMethod: "bankily",
    customerName: "زبون نقدي",
    itemCount: 1,
  },
  {
    id: "V-1046",
    createdAt: "10:54",
    total: 18400,
    paymentMethod: "credit",
    customerName: "محمد ولد أحمد",
    itemCount: 7,
  },
  {
    id: "V-1045",
    createdAt: "10:16",
    total: 3500,
    paymentMethod: "cash",
    customerName: "زبون نقدي",
    itemCount: 2,
  },
];

export const demoMovements: MovementRecord[] = [
  {
    id: "M-230",
    createdAt: "اليوم، 09:20",
    type: "receipt",
    productName: "سكر ناعم 1 كغ",
    quantityPieces: 100,
    piecesPerCarton: 20,
    to: "warehouse",
    reference: "REC-0032",
    note: "استلام من المورد إلى المخزن الرئيسي",
  },
  {
    id: "M-229",
    createdAt: "أمس، 17:10",
    type: "transfer",
    productName: "حليب طويل الأجل",
    quantityPieces: 48,
    piecesPerCarton: 24,
    from: "warehouse",
    to: "boutique",
    reference: "TR-0018",
    note: "تحويل مكتمل إلى البوتيك",
  },
  {
    id: "M-228",
    createdAt: "أمس، 12:45",
    type: "receipt",
    productName: "مسحوق تنظيف 2 كغ",
    quantityPieces: 24,
    piecesPerCarton: 8,
    to: "boutique",
    reference: "REC-0031",
    note: "شراء من السوق واستلام مباشر في البوتيك",
  },
];
