import type { Db, Document } from "mongodb";
import type { ReportFilters, ReportResponse, ReportRow, ReportType } from "../app/report-types.ts";

const TYPES: ReportType[] = ["overview", "sales", "purchases", "product-sales", "stock", "profit", "debts", "party-ledger", "financial", "expenses", "returns"];
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const text = (v: string | null) => (v ?? "").trim();
const n = (v: unknown) => Number(v ?? 0);
const isoDate = (value: string, next = false) => { const d = new Date(`${value}T00:00:00.000Z`); if (Number.isNaN(d.valueOf()) || d.toISOString().slice(0, 10) !== value) throw new Error("التاريخ غير صالح"); if (next) d.setUTCDate(d.getUTCDate() + 1); return d; };
export function parseReportFilters(url: URL): ReportFilters {
  const type = text(url.searchParams.get("type")) as ReportType;
  if (!TYPES.includes(type)) throw new Error("نوع التقرير غير صالح");
  const from = text(url.searchParams.get("from")), to = text(url.searchParams.get("to"));
  if (type !== "debts" && (!DATE.test(from) || !DATE.test(to))) throw new Error("الفترة مطلوبة");
  if (from && to && isoDate(from) > isoDate(to)) throw new Error("بداية الفترة يجب ألا تتجاوز نهايتها");
  if (from && to && (isoDate(to).valueOf() - isoDate(from).valueOf()) / 86400000 > 3660) throw new Error("الفترة طويلة جدًا");
  const page = Number(url.searchParams.get("page") ?? 1), pageSize = Number(url.searchParams.get("pageSize") ?? 100);
  if (!Number.isInteger(page) || page < 1 || !Number.isInteger(pageSize) || pageSize < 1 || pageSize > 200) throw new Error("إعدادات الصفحة غير صالحة");
  const pick = <T extends string>(key: string, allowed: T[], fallback?: T) => { const value = text(url.searchParams.get(key)); if (!value) return fallback; if (!allowed.includes(value as T)) throw new Error(`الفلتر ${key} غير صالح`); return value as T; };
  return { type, from: from || undefined, to: to || undefined, partyId: text(url.searchParams.get("partyId")) || undefined, productId: text(url.searchParams.get("productId")) || undefined, warehouseId: text(url.searchParams.get("warehouseId")) || undefined, paymentAccountId: text(url.searchParams.get("paymentAccountId")) || undefined, movementType: text(url.searchParams.get("movementType")) || undefined, direction: pick("direction", ["in", "out"]), groupBy: pick("groupBy", ["invoice", "product", "party"], "invoice"), sortBy: pick("sortBy", ["quantity", "sales", "name", "profit"], "quantity"), debtSide: pick("debtSide", ["receivable", "payable", "clear"]), expenseType: pick("expenseType", ["once", "recurring"]), search: text(url.searchParams.get("search")) || undefined, page, pageSize };
}
const dateExpr = (f: ReportFilters) => ({ $and: [{ $gte: [{ $convert: { input: "$occurredAt", to: "date", onError: null, onNull: null } }, isoDate(f.from!)] }, { $lt: [{ $convert: { input: "$occurredAt", to: "date", onError: null, onNull: null } }, isoDate(f.to!, true)] }] });
const page = (rows: ReportRow[], f: ReportFilters) => rows.slice((f.page - 1) * f.pageSize, f.page * f.pageSize);
const meta = (rows: ReportRow[], f: ReportFilters, extra = {}) => ({ page: f.page, pageSize: f.pageSize, totalRows: rows.length, totalPages: Math.max(1, Math.ceil(rows.length / f.pageSize)), ...extra });
async function docs(db: Db, f: ReportFilters, kinds: string[]) { const match: Document = { kind: { $in: kinds }, status: "posted", $expr: dateExpr(f) }; if (f.partyId) match.partyId = f.partyId; if (f.warehouseId) match.warehouseId = f.warehouseId; if (f.paymentAccountId) match.paymentMethod = f.paymentAccountId; if (f.productId) match["lines.productId"] = f.productId; return db.collection("documents").find(match).sort({ occurredAt: -1 }).toArray(); }
export async function buildReport(db: Db, f: ReportFilters): Promise<ReportResponse> {
  if (f.type === "debts") { const query: Document = {}; if (f.search) query.$or = [{ name: { $regex: f.search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), $options: "i" } }, { phone: { $regex: f.search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") } }]; if (f.debtSide === "receivable") query.receivable = { $gt: 0 }; if (f.debtSide === "payable") query.payable = { $gt: 0 }; if (f.debtSide === "clear") query.$and = [{ receivable: { $lte: 0 } }, { payable: { $lte: 0 } }]; const parties = await db.collection("parties").find(query).sort({ name: 1 }).toArray(); const rows = parties.map(p => ({ id: String(p.id), partyId: String(p.id), name: String(p.name), phone: String(p.phone ?? ""), receivable: n(p.receivable), payable: n(p.payable), net: n(p.receivable) - n(p.payable), lastMovement: String(p.lastMovementAt ?? "") })); return { report: f.type, from: null, to: null, summary: { receivable: rows.reduce((s,r)=>s+n(r.receivable),0), payable: rows.reduce((s,r)=>s+n(r.payable),0), net: rows.reduce((s,r)=>s+n(r.net),0) }, rows: page(rows,f), meta: meta(rows,f) }; }
  if (f.type === "party-ledger") { if(!f.partyId) throw new Error("يجب اختيار الطرف"); const party=await db.collection("parties").findOne({id:f.partyId});if(!party)throw new Error("الطرف غير موجود");const raw=await docs(db,f,["sale","purchase","return","payment","offset","settlement"]);const rows=raw.map(d=>{let debit=0,credit=0;if(d.kind==="sale")debit=n(d.dueTotal);else if(d.kind==="purchase")credit=n(d.dueTotal);else if(d.kind==="return")credit=Math.max(0,n(d.total)-n(d.paidTotal));else if(d.kind==="payment"||d.kind==="settlement"){if(String(d.title).includes("دفع لنا"))credit=n(d.total);else debit=n(d.total)}else if(d.kind==="offset"){debit=n(d.total);credit=n(d.total)}return{id:String(d.id),documentId:String(d.id),occurredAt:String(d.occurredAt),movementType:String(d.kind),documentNumber:String(d.number),description:String(d.title??d.partyName??""),debit,credit,paymentMethod:String(d.paymentMethod??"")}});return{report:f.type,from:f.from!,to:f.to!,summary:{name:String(party.name),phone:String(party.phone??""),receivable:n(party.receivable),payable:n(party.payable),net:n(party.receivable)-n(party.payable)},rows:page(rows,f),meta:meta(rows,f)};}
  if (f.type === "stock") { const match: Document = { $expr: dateExpr(f) }; if(f.productId) match.productId=f.productId;if(f.warehouseId)match.warehouseId=f.warehouseId;if(f.movementType)match.type=f.movementType; const raw=await db.collection("stockMovements").aggregate([{ $match:match },{$lookup:{from:"products",localField:"productId",foreignField:"id",as:"productRef"}},{$sort:{occurredAt:-1}}]).toArray(); const rows=raw.map(x=>({id:String(x.id),documentId:String(x.documentId),occurredAt:String(x.occurredAt),sku:String(x.productRef?.[0]?.sku??""),product:String(x.productName),warehouse:String(x.warehouseName),movementType:String(x.type),before:n(x.balanceBefore),change:n(x.quantityDelta),after:n(x.balanceAfter),documentNumber:String(x.documentNumber)})); return {report:f.type,from:f.from!,to:f.to!,summary:{movements:rows.length,incoming:rows.reduce((s,r)=>s+Math.max(0,n(r.change)),0),outgoing:rows.reduce((s,r)=>s+Math.abs(Math.min(0,n(r.change))),0)},rows:page(rows,f),meta:meta(rows,f)}; }
  if (f.type === "financial") { const match:Document={$expr:dateExpr(f)};if(f.paymentAccountId)match.paymentMethod=f.paymentAccountId;if(f.movementType)match.type=f.movementType;if(f.direction)match.direction=f.direction;const raw=await db.collection("financialMovements").find(match).sort({occurredAt:-1}).toArray();const rows=raw.map(x=>({id:String(x.id),documentId:String(x.documentId),occurredAt:String(x.occurredAt),paymentMethod:String(x.paymentMethod),movementType:String(x.type),incoming:x.direction==="in"?n(x.amount):0,outgoing:x.direction==="out"?n(x.amount):0,party:String(x.partyName??""),documentNumber:String(x.documentNumber??"")}));const operating=rows.filter(r=>!String(r.movementType).startsWith("transfer-"));const groups=new Map<string,{account:string;incoming:number;outgoing:number;net:number}>();for(const r of rows){const key=String(r.paymentMethod),g=groups.get(key)??{account:key,incoming:0,outgoing:0,net:0};g.incoming+=n(r.incoming);g.outgoing+=n(r.outgoing);g.net=g.incoming-g.outgoing;groups.set(key,g)}return{report:f.type,from:f.from!,to:f.to!,summary:{incoming:rows.reduce((s,r)=>s+n(r.incoming),0),outgoing:rows.reduce((s,r)=>s+n(r.outgoing),0),net:rows.reduce((s,r)=>s+n(r.incoming)-n(r.outgoing),0),operatingIncoming:operating.reduce((s,r)=>s+n(r.incoming),0),operatingOutgoing:operating.reduce((s,r)=>s+n(r.outgoing),0),operatingNet:operating.reduce((s,r)=>s+n(r.incoming)-n(r.outgoing),0)},rows:page(rows,f),meta:meta(rows,f,{accountTotals:[...groups.values()]})}; }
  const all=await docs(db,f,f.type==="expenses"?["expense"]:f.type==="returns"?["return"]:f.type==="purchases"?["purchase"]:["sale","return"]);
  if(f.type==="sales"||f.type==="purchases"||f.type==="expenses"||f.type==="returns"){let selected=all;if(f.type==="expenses"&&f.expenseType)selected=all.filter(d=>f.expenseType==="recurring"?Boolean(d.recurringId):!d.recurringId);const rows=selected.map(d=>f.type==="returns"?{id:String(d.id),documentId:String(d.id),occurredAt:String(d.occurredAt),number:String(d.number),originalDocument:String(d.parentDocumentId??""),party:String(d.partyName??""),products:Array.isArray(d.lines)?d.lines.length:0,quantity:(d.lines??[]).reduce((s:number,l:Document)=>s+n(l.quantity),0),total:n(d.total)}:{id:String(d.id),documentId:String(d.id),number:String(d.number),occurredAt:String(d.occurredAt),party:String(d.partyName??(f.type==="sales"?"بيع مباشر":"")),warehouse:String(d.warehouseName??""),paymentMethod:String(d.paymentMethod??""),title:String(d.title??""),recurring:Boolean(d.recurringId),total:n(d.total),paid:n(d.paidTotal),due:n(d.dueTotal)});return{report:f.type,from:f.from!,to:f.to!,summary:{count:rows.length,total:rows.reduce((s,r)=>s+n(r.total),0),paid:rows.reduce((s,r)=>s+n(r.paid),0),due:rows.reduce((s,r)=>s+n(r.due),0),quantity:rows.reduce((s,r)=>s+n(r.quantity),0),once:rows.filter(r=>!r.recurring).reduce((s,r)=>s+n(r.total),0),recurring:rows.filter(r=>r.recurring).reduce((s,r)=>s+n(r.total),0)},rows:page(rows,f),meta:meta(rows,f)};}
  const sales=all.filter(d=>d.kind==="sale"),returns=all.filter(d=>d.kind==="return"); const productMap=new Map<string,ReportRow>();for(const d of [...sales,...returns])for(const l of d.lines??[]){if(f.productId&&l.productId!==f.productId)continue;const key=String(l.productId),r=productMap.get(key)??{productId:key,sku:"",product:String(l.description),soldQuantity:0,returnedQuantity:0,netQuantity:0,sales:0,returns:0,netSales:0,averagePrice:0};const sign=d.kind==="return"?-1:1;r[d.kind==="return"?"returnedQuantity":"soldQuantity"]=n(r[d.kind==="return"?"returnedQuantity":"soldQuantity"])+n(l.quantity);r[d.kind==="return"?"returns":"sales"]=n(r[d.kind==="return"?"returns":"sales"])+n(l.lineTotal);r.netQuantity=n(r.netQuantity)+sign*n(l.quantity);r.netSales=n(r.netSales)+sign*n(l.lineTotal);r.averagePrice=n(r.soldQuantity)?n(r.sales)/n(r.soldQuantity):0;productMap.set(key,r)}
  if(f.type==="product-sales"){const products=await db.collection("products").find({id:{$in:[...productMap.keys()]}}).project({id:1,sku:1}).toArray();for(const p of products){const r=productMap.get(String(p.id));if(r)r.sku=String(p.sku??"")}const rows=[...productMap.values()];rows.sort((a,b)=>f.sortBy==="name"?String(a.product).localeCompare(String(b.product),"ar"):n(b[f.sortBy==="sales"?"netSales":"netQuantity"])-n(a[f.sortBy==="sales"?"netSales":"netQuantity"]));return{report:f.type,from:f.from!,to:f.to!,summary:{products:rows.length,quantity:rows.reduce((s,r)=>s+n(r.netQuantity),0),sales:rows.reduce((s,r)=>s+n(r.netSales),0)},rows:page(rows,f),meta:meta(rows,f)}}
  const profitLines:ReportRow[]=[];for(const d of [...sales,...returns])for(const l of d.lines??[]){const sign=d.kind==="return"?-1:1,costKnown=Number.isFinite(l.costAtSale);profitLines.push({id:`${d.id}-${l.id}`,documentId:String(d.id),number:String(d.number),occurredAt:String(d.occurredAt),partyId:String(d.partyId??""),party:String(d.partyName??"بيع مباشر"),productId:String(l.productId),product:String(l.description),quantity:sign*n(l.quantity),revenue:sign*n(l.lineTotal),cost:costKnown?sign*n(l.quantity)*n(l.costAtSale):0,profit:costKnown?sign*(n(l.lineTotal)-n(l.quantity)*n(l.costAtSale)):0,costKnown,unknownRevenue:costKnown?0:n(l.lineTotal)});}const key=(r:ReportRow)=>f.groupBy==="product"?String(r.productId):f.groupBy==="party"?String(r.partyId||"direct"):String(r.documentId);const grouped=new Map<string,ReportRow>();for(const r of profitLines){const k=key(r),g=grouped.get(k)??{id:k,documentId:r.documentId,number:r.number,occurredAt:r.occurredAt,party:r.party,product:r.product,quantity:0,revenue:0,cost:0,profit:0,invoiceCount:0,unknownRevenue:0,costKnown:true};g.quantity=n(g.quantity)+n(r.quantity);g.revenue=n(g.revenue)+n(r.revenue);g.cost=n(g.cost)+n(r.cost);g.profit=n(g.profit)+n(r.profit);g.unknownRevenue=n(g.unknownRevenue)+n(r.unknownRevenue);g.costKnown=Boolean(g.costKnown)&&Boolean(r.costKnown);g.invoiceCount=n(g.invoiceCount)+1;g.margin=n(g.revenue)?n(g.profit)/n(g.revenue)*100:0;grouped.set(k,g)}const prows=[...grouped.values()].sort((a,b)=>n(b.profit)-n(a.profit));if(f.type==="profit")return{report:f.type,from:f.from!,to:f.to!,summary:{revenue:prows.reduce((s,r)=>s+n(r.revenue),0),cost:prows.reduce((s,r)=>s+n(r.cost),0),profit:prows.reduce((s,r)=>s+n(r.profit),0),unknownRevenue:prows.reduce((s,r)=>s+n(r.unknownRevenue),0),unknownRows:prows.filter(r=>!r.costKnown).length},rows:page(prows,f),meta:meta(prows,f)};
  const financial=await buildReport(db,{...f,type:"financial"});const byDay=new Map<string,ReportRow>();for(const d of [...sales,...returns,...await docs(db,f,["purchase","expense"])]){const day=String(d.occurredAt).slice(0,10),r=byDay.get(day)??{date:day,sales:0,purchases:0,expenses:0,received:0,paid:0,net:0};if(d.kind==="sale")r.sales=n(r.sales)+n(d.total);if(d.kind==="return")r.sales=n(r.sales)-n(d.total);if(d.kind==="purchase")r.purchases=n(r.purchases)+n(d.total);if(d.kind==="expense")r.expenses=n(r.expenses)+n(d.total);byDay.set(day,r)}for(const r of financial.rows){const day=String(r.occurredAt).slice(0,10),g=byDay.get(day)??{date:day,sales:0,purchases:0,expenses:0,received:0,paid:0,net:0};if(!String(r.movementType).startsWith("transfer-")){g.received=n(g.received)+n(r.incoming);g.paid=n(g.paid)+n(r.outgoing);g.net=n(g.received)-n(g.paid)}byDay.set(day,g)}const rows=[...byDay.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)));return{report:"overview",from:f.from!,to:f.to!,summary:{sales:sales.reduce((s,d)=>s+n(d.total),0),purchases:(await docs(db,f,["purchase"])).reduce((s,d)=>s+n(d.total),0),expenses:(await docs(db,f,["expense"])).reduce((s,d)=>s+n(d.total),0),returns:returns.reduce((s,d)=>s+n(d.total),0),received:n(financial.summary.operatingIncoming),paid:n(financial.summary.operatingOutgoing),cashFlow:n(financial.summary.operatingNet),profit:prows.reduce((s,r)=>s+n(r.profit),0),unknownRevenue:prows.reduce((s,r)=>s+n(r.unknownRevenue),0)},rows:page(rows,f),meta:meta(rows,f)};
}
