import initSqlJs, { type Database } from "sql.js";
import { createRequire } from "node:module";
import { isAbsolute, join } from "node:path";
import type { ClientSession, Db } from "mongodb";
import { rebuildCounters } from "../lib/backup.ts";

export const SQLITE_MAGIC = Buffer.from("SQLite format 3\0", "ascii");
export const MAX_LEGACY_BYTES = 50 * 1024 * 1024;
export const LEGACY_SUPPORTED_TABLES = ["itemsTB","storesTB","stores_itemsTB","customerTB","supplierTB","suppliersTB","BankTB","PayMethods","buyBillTB","items_BuyTB","purchBillTB","items_purchTB","safeTB","process_TypeTB","process_MainType","companyTB"];
const financialReview = ["tblBankDeposit","tblBankConvert","tblBankConvertToSafe","customerAccountTB","customerSolfaTB","suppliersAccountTB","suppliersSolfaTB"];
const unsupported = ["userTB","authTB","EmpTBs","Emp_salaryTB","Emp_mrtbatTB","presenceTB","MaintainceTB","tblPrinter","tblPrinterAccounts","Units","items_UnitsTB","NotesTB","ShowBillTB","items_ShowBillTB"];
export function detectLegacyDatabase(bytes: Uint8Array) { return bytes.length >= 16 && Buffer.from(bytes.subarray(0, 16)).equals(SQLITE_MAGIC); }

/** Resolve the actual runtime asset through Node's package resolver (including standalone deployments). */
export function resolveSqlJsWasmPath() {
  const runtimeRequire = createRequire(join(process.cwd(), "package.json"));
  const wasmPath = runtimeRequire.resolve("sql.js/dist/sql-wasm.wasm");
  if (!isAbsolute(wasmPath)) throw new Error("sql.js WASM path must be absolute");
  return wasmPath;
}

async function open(bytes: Uint8Array) { if (bytes.byteLength > MAX_LEGACY_BYTES) throw new Error("ملف SQLite أكبر من الحد المسموح"); if (!detectLegacyDatabase(bytes)) throw new Error("الملف ليس قاعدة SQLite 3"); const SQL = await initSqlJs({ locateFile: () => resolveSqlJsWasmPath() }); return new SQL.Database(bytes); }
type Row = Record<string, unknown>;
const tables = (db: Database) => db.exec("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")[0]?.values.flat().map(String) ?? [];
const quote = (name: string) => `"${name.replaceAll('"','""')}"`;
function rows(db: Database, table: string): Row[] { const result = db.exec(`SELECT * FROM ${quote(table)}`)[0]; return result ? result.values.map(values => Object.fromEntries(result.columns.map((c,i)=>[c, values[i]]))) : []; }
const get = (r: Row, ...names: string[]) => { const map = new Map(Object.entries(r).map(([k,v])=>[k.toLowerCase(),v])); for (const n of names) if (map.has(n.toLowerCase())) return map.get(n.toLowerCase()); return null; };
const text = (v: unknown) => v == null ? "" : String(v).trim(); const num = (v: unknown) => { const n=Number(v); return Number.isFinite(n)?n:0; };
const date = (v: unknown) => { const raw=text(v), deterministic=/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(raw)?`${raw.replace(" ","T")}Z`:raw; const d=new Date(deterministic); return Number.isNaN(d.valueOf()) ? new Date(0).toISOString() : d.toISOString(); };
const normalize = (v: unknown) => text(v).toLocaleLowerCase("ar").replace(/\s+/g," ");
const key = (table:string,id:unknown) => `dataacc:${table}:${text(id)}`;
const id = (prefix:string, legacyKey:string) => `${prefix}-legacy-${Buffer.from(legacyKey).toString("base64url")}`;
const count = (db:Database, available:Set<string>, name:string) => available.has(name)?rows(db,name).length:0;
export type LegacyPreview = { format:"dataacc-sqlite"; groups:Array<{key:string;label:string;count:number;status:"ready"|"unsupported"|"review"}>; warnings:string[]; tables:string[] };
export async function inspectLegacyDatabase(bytes: Uint8Array): Promise<LegacyPreview> { const db=await open(bytes); try { const names=tables(db), a=new Set(names); const groups=[
 ["products","المنتجات",count(db,a,"itemsTB"),"ready"],["warehouses","المخازن",count(db,a,"storesTB"),"ready"],["stocks","أرصدة المخازن",count(db,a,"stores_itemsTB"),"ready"],["sales","فواتير البيع",count(db,a,"buyBillTB"),"ready"],["saleLines","عناصر فواتير البيع",count(db,a,"items_BuyTB"),"ready"],["purchases","فواتير الشراء",count(db,a,"purchBillTB"),"ready"],["purchaseLines","عناصر الشراء",count(db,a,"items_purchTB"),"ready"],["parties","العملاء والموردون",count(db,a,"customerTB")+count(db,a,a.has("suppliersTB")?"suppliersTB":"supplierTB"),"ready"],["accounts","الحسابات والبنوك",count(db,a,"BankTB"),"ready"],["expenses","المصاريف",count(db,a,"safeTB"),"ready"],
 ...unsupported.filter(x=>a.has(x)).map(x=>[x,x,count(db,a,x),"unsupported"]), ...financialReview.filter(x=>a.has(x)).map(x=>[x,x,count(db,a,x),"review"])
 ].map(([key,label,count,status])=>({key:String(key),label:String(label),count:Number(count),status:status as "ready"|"unsupported"|"review"})); return {format:"dataacc-sqlite",groups,warnings:financialReview.filter(x=>a.has(x)).map(x=>`${x}: بيانات مالية تحتاج مراجعة — لن يتم استيرادها تلقائيًا`),tables:names}; } finally { db.close(); } }

export async function executeLegacyImport(db: Db, session: ClientSession, bytes: Uint8Array, stockPolicy:"current"|"imported"="current") {
 const sqlite=await open(bytes); try { const available=new Set(tables(sqlite)); const read=(t:string)=>available.has(t)?rows(sqlite,t):[]; const now=new Date();
  const existingWarehouses=await db.collection<{_id:string;[key:string]:unknown}>("warehouses").find({}, {session}).toArray(), warehouseMap=new Map<string,string>();
  for(const r of read("storesTB")){const lk=key("storesTB",get(r,"id"));let found: Row|null=await db.collection<{_id:string;[key:string]:unknown}>("warehouses").findOne({legacyKey:lk},{session});if(!found){const name=text(get(r,"title","name","StoreName"))||`مخزن ${text(get(r,"id"))}`;found=existingWarehouses.find(w=>normalize(w.name)===normalize(name))??null;if(!found){const wid=id("wh",lk);await db.collection<{_id:string;[key:string]:unknown}>("warehouses").insertOne({_id:wid,name,isSalesDefault:false,legacyKey:lk,createdAt:now},{session});found={_id:wid,name};}}warehouseMap.set(text(get(r,"id")),String(found._id));}
  if(!warehouseMap.size){const fallback=existingWarehouses.find(w=>w.isSalesDefault)??existingWarehouses[0];if(fallback)warehouseMap.set("",String(fallback._id));}
  const partyMap=new Map<string,string>(); for(const [table,role] of [["customerTB","customer"],[available.has("suppliersTB")?"suppliersTB":"supplierTB","supplier"]] as const) for(const r of read(table)){const old=text(get(r,"id")),lk=key(table,get(r,"id")),name=text(get(r,"title","name","CustomerName","SupplierName"))||`${role==="customer"?"عميل":"مورد"} ${old}`,phone=text(get(r,"phone","tel","mobile"));let found: Row|null=await db.collection("parties").findOne({$or:[{legacyKey:lk},...(phone?[{phone}]:[]),{nameNormalized:normalize(name),roles:role}]},{session});if(!found){const pid=id("party",lk);await db.collection("parties").insertOne({id:pid,name,nameNormalized:normalize(name),phone,roles:[role],receivable:0,payable:0,net:0,legacyKey:lk,legacy:{source:"dataacc-sqlite",table,id:get(r,"id")},createdAt:now},{session});found={id:pid};}partyMap.set(`${role}:${old}`,String(found.id));}
  const accountMap=new Map<string,string>();for(const r of read("BankTB")){const old=text(get(r,"id")),lk=key("BankTB",get(r,"id")),name=text(get(r,"BankName","title","name"))||`حساب ${old}`;let found: Row|null=await db.collection("paymentAccounts").findOne({$or:[{legacyKey:lk},{nameNormalized:normalize(name)},{name}]},{session});if(!found){const aid=id("account",lk);await db.collection("paymentAccounts").insertOne({id:aid,code:`legacy-${old}`,name,nameNormalized:normalize(name),color:"#64748b",icon:"wallet",isActive:true,balance:num(get(r,"rasid")),legacyKey:lk,legacy:{source:"dataacc-sqlite",table:"BankTB",id:get(r,"id"),accountNumber:text(get(r,"NumCompte"))},createdAt:now},{session});found={id:aid};}accountMap.set(old,String(found.id));}
  const existingProducts=await db.collection("products").find({}, {session}).toArray(), barcodes=new Map<string,Row>(existingProducts.filter(p=>text(p.barcode)).map(p=>[text(p.barcode),p])), productMap=new Map<string,string>();let sequence=Math.max(0,...existingProducts.map(p=>/^\d+$/.test(text(p.sku))?num(p.sku):0));
  for(const r of read("itemsTB")){const old=text(get(r,"id")),lk=key("itemsTB",get(r,"id")),candidate=text(get(r,"barcode"))||text(get(r,"code"));let found: Row|null=await db.collection("products").findOne({legacyKey:lk},{session})??barcodes.get(candidate)??null;if(!found){sequence++;const pid=id("product",lk), product={id:pid,name:text(get(r,"title"))||`منتج ${old}`,sku:String(sequence).padStart(4,"0"),barcode:candidate&&!barcodes.has(candidate)?candidate:"",pieceCost:null,piecePrice:num(get(r,"priceUnit"))||null,stocks:{},legacyOpeningCost:num(get(r,"last_cost","start_Cost"))||null,legacyKey:lk,legacy:{source:"dataacc-sqlite",table:"itemsTB",id:get(r,"id"),originalCode:text(get(r,"code"))},createdAt:now};await db.collection("products").insertOne(product,{session});found=product;if(candidate)barcodes.set(candidate,product);}productMap.set(old,String(found.id));}
  for(const r of read("stores_itemsTB")){const pid=productMap.get(text(get(r,"item_idFK"))),wid=warehouseMap.get(text(get(r,"store_idFK")));if(!pid||!wid)continue;const qty=num(get(r,"qty")),p=await db.collection("products").findOne({id:pid},{session});const current=num((p?.stocks as Row|undefined)?.[wid]);if(current!==0&&current!==qty&&stockPolicy==="current")continue;await db.collection("products").updateOne({id:pid},{$set:{[`stocks.${wid}`]:qty}},{session});const lk=key("stores_itemsTB",get(r,"id")||`${get(r,"store_idFK")}:${get(r,"item_idFK")}`);if(!await db.collection("stockMovements").findOne({legacyKey:lk},{session}))await db.collection("stockMovements").insertOne({id:id("movement",lk),legacyKey:lk,documentId:"legacy-opening",documentNumber:"LEG-OPEN",warehouseId:wid,warehouseName:"ترحيل قديم",productId:pid,productName:p?.name??"",type:"legacy-opening",quantityDelta:qty,balanceBefore:0,balanceAfter:qty,occurredAt:now.toISOString()},{session});}
  const importDocs=async(kind:"sale"|"purchase",head:string,lineTable:string,fk:string,partyRole:string)=>{const lineRows=read(lineTable);const perDay=new Map<string,number>();for(const h of read(head)){const old=text(get(h,"id")),lk=key(head,get(h,"id"));if(await db.collection("documents").findOne({legacyKey:lk},{session}))continue;const occurredAt=date(get(h,"Date")),businessDate=occurredAt.slice(0,10),lines=lineRows.filter(l=>text(get(l,fk))===old).map(l=>{const quantity=num(get(l,"qty")),unitPrice=num(get(l,kind==="sale"?"price_Buy":"price_purch")),cost=kind==="sale"?num(get(l,"LastCost")):null;return{id:id("line",`${lk}:${text(get(l,"id"))}`),productId:productMap.get(text(get(l,"item_idFK")))??null,description:text(get(l,"title")),quantity,unitPrice,lineTotal:Math.round(quantity*unitPrice),...(kind==="sale"?{costAtSale:cost != null && cost > 0?cost:null,grossProfit:cost != null && cost > 0?Math.round(quantity*unitPrice-quantity*cost):null}:{})};});const calculated=lines.reduce((s,l)=>s+l.lineTotal,0),legacyTotal=num(get(h,kind==="sale"?"priceBillAfterKhasm":"priceBill","total")),total=legacyTotal||calculated,paid=num(get(h,"PaidMony")),due=num(get(h,"remainMony"))||Math.max(0,total-paid),seq=(perDay.get(businessDate)??0)+1;perDay.set(businessDate,seq);await db.collection("documents").insertOne({id:id("document",lk),legacyKey:lk,legacyBillCode:text(get(h,"Billcode")),number:`LEG-${kind==="sale"?"SAL":"PUR"}-${old}`,kind,status:"posted",partyId:partyMap.get(`${partyRole}:${text(get(h,kind==="sale"?"CustomerFK":"SuppFK"))}`)??null,partyName:null,warehouseId:warehouseMap.get(text(get(h,"StoreFK")))??warehouseMap.values().next().value??null,warehouseName:null,destinationWarehouseId:null,destinationWarehouseName:null,parentDocumentId:null,paymentMethod:null,title:null,total,dueTotal:due,paidTotal:paid,occurredAt,businessDate,...(kind==="sale"?{dailySequence:seq}:{}),lines,legacy:{source:"dataacc-sqlite",table:head,id:get(h,"id")}}, {session});}};
  await importDocs("sale","buyBillTB","items_BuyTB","BuyFK","customer");await importDocs("purchase","purchBillTB","items_purchTB","purchFK","supplier");
  const purchases=await db.collection("documents").find({kind:"purchase",status:"posted",legacyKey:{$exists:true}},{session}).sort({occurredAt:-1}).toArray(),seen=new Set<string>();for(const d of purchases)for(const l of d.lines as Row[]){const pid=text(l.productId);if(pid&&!seen.has(pid)){seen.add(pid);await db.collection("products").updateOne({id:pid,$or:[{lastPurchaseAt:{$exists:false}},{lastPurchaseAt:{$lt:d.occurredAt}}]},{$set:{lastPurchaseCost:num(l.unitPrice),lastPurchaseAt:d.occurredAt}},{session});}}
  for(const r of read("safeTB")){const lk=key("safeTB",get(r,"id"));if(await db.collection("documents").findOne({legacyKey:lk},{session}))continue;const amount=num(get(r,"QtyMoney"));if(amount<=0)continue;const title=text(get(r,"Pand"))||"مصروف قديم",occurredAt=date(get(r,"Date")),aid=accountMap.get(text(get(r,"BankID")))??null;await db.collection("documents").insertOne({id:id("document",lk),legacyKey:lk,number:`LEG-EXP-${text(get(r,"id"))}`,kind:"expense",status:"posted",partyId:null,partyName:null,warehouseId:null,warehouseName:null,destinationWarehouseId:null,destinationWarehouseName:null,parentDocumentId:null,paymentMethod:aid,title,total:amount,dueTotal:0,paidTotal:amount,occurredAt,lines:[{id:id("line",lk),productId:null,description:title,quantity:1,unitPrice:amount,lineTotal:amount}]},{session});}
  await rebuildCounters(db,session);return {products:productMap.size,warehouses:warehouseMap.size,parties:partyMap.size,accounts:accountMap.size};
 } finally {sqlite.close();}}
